paths:
  /Messages:
    post:
      tags:
        - Message
      summary: Create a new instance of the model and persist it into the data source.
      operationId: Message.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/Message'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Message'
      deprecated: false
    put:
      tags:
        - Message
      summary: >-
        Update an existing model instance or insert a new one into the data
        source.
      operationId: Message.upsert
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/Message'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Message'
      deprecated: false
    get:
      tags:
        - Message
      summary: Find all instances of the model matched by filter from the data source.
      operationId: Message.find
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Message'
      deprecated: false
  '/Messages/{id}/exists':
    get:
      tags:
        - Message
      summary: Check whether a model instance exists in the data source.
      operationId: 'Message.exists__get_Messages_{id}_exists'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
  '/Messages/{id}':
    head:
      tags:
        - Message
      summary: Check whether a model instance exists in the data source.
      operationId: 'Message.exists__head_Messages_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
    get:
      tags:
        - Message
      summary: Find a model instance by id from the data source.
      operationId: Message.findById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: filter
          in: query
          description: Filter defining fields and include
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Message'
      deprecated: false
    delete:
      tags:
        - Message
      summary: Delete a model instance by id from the data source.
      operationId: Message.deleteById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    put:
      tags:
        - Message
      summary: >-
        Update attributes for a model instance and persist it into the data
        source.
      operationId: Message.prototype.updateAttributes
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/Message'
        - name: id
          in: path
          description: PersistedModel id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Message'
      deprecated: false
  /Messages/findOne:
    get:
      tags:
        - Message
      summary: Find first instance of the model matched by filter from the data source.
      operationId: Message.findOne
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Message'
      deprecated: false
  /Messages/update:
    post:
      tags:
        - Message
      summary: Update instances of the model matched by where from the data source.
      operationId: Message.updateAll
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/Message'
      responses:
        '200':
          description: Request was successful
          schema:
            description: The number of instances updated
            type: object
      deprecated: false
  /Messages/count:
    get:
      tags:
        - Message
      summary: Count instances of the model matched by where from the data source.
      operationId: Message.count
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              count:
                type: number
                format: double
      deprecated: false
  /Messages/change-stream:
    post:
      tags:
        - Message
      summary: Create a change stream.
      operationId: Message.createChangeStream__post_Messages_change-stream
      parameters:
        - name: options
          in: formData
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: file
      deprecated: false
    get:
      tags:
        - Message
      summary: Create a change stream.
      operationId: Message.createChangeStream__get_Messages_change-stream
      parameters:
        - name: options
          in: query
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: file
      deprecated: false
  /Messages/greet:
    get:
      tags:
        - Message
      operationId: Message.greet
      parameters:
        - name: msg
          in: query
          required: false
          type: string
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              greeting:
                type: string
      deprecated: false
  /tests:
    post:
      tags:
        - test
      summary: Create a new instance of the model and persist it into the data source.
      operationId: test.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/test'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/test'
      deprecated: false
    put:
      tags:
        - test
      summary: >-
        Update an existing model instance or insert a new one into the data
        source.
      operationId: test.upsert
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/test'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/test'
      deprecated: false
    get:
      tags:
        - test
      summary: Find all instances of the model matched by filter from the data source.
      operationId: test.find
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/test'
      deprecated: false
  '/tests/{id}/exists':
    get:
      tags:
        - test
      summary: Check whether a model instance exists in the data source.
      operationId: 'test.exists__get_tests_{id}_exists'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
  '/tests/{id}':
    head:
      tags:
        - test
      summary: Check whether a model instance exists in the data source.
      operationId: 'test.exists__head_tests_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
    get:
      tags:
        - test
      summary: Find a model instance by id from the data source.
      operationId: test.findById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: filter
          in: query
          description: Filter defining fields and include
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/test'
      deprecated: false
    delete:
      tags:
        - test
      summary: Delete a model instance by id from the data source.
      operationId: test.deleteById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    put:
      tags:
        - test
      summary: >-
        Update attributes for a model instance and persist it into the data
        source.
      operationId: test.prototype.updateAttributes
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/test'
        - name: id
          in: path
          description: PersistedModel id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/test'
      deprecated: false
  /tests/findOne:
    get:
      tags:
        - test
      summary: Find first instance of the model matched by filter from the data source.
      operationId: test.findOne
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/test'
      deprecated: false
  /tests/update:
    post:
      tags:
        - test
      summary: Update instances of the model matched by where from the data source.
      operationId: test.updateAll
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/test'
      responses:
        '200':
          description: Request was successful
          schema:
            description: The number of instances updated
            type: object
      deprecated: false
  /tests/count:
    get:
      tags:
        - test
      summary: Count instances of the model matched by where from the data source.
      operationId: test.count
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              count:
                type: number
                format: double
      deprecated: false
  /tests/change-stream:
    post:
      tags:
        - test
      summary: Create a change stream.
      operationId: test.createChangeStream__post_tests_change-stream
      parameters:
        - name: options
          in: formData
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: file
      deprecated: false
    get:
      tags:
        - test
      summary: Create a change stream.
      operationId: test.createChangeStream__get_tests_change-stream
      parameters:
        - name: options
          in: query
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: file
      deprecated: false
definitions:
  Message:
    properties:
      p1:
        type: number
        format: double
      p2:
        type: number
        format: double
      id:
        type: number
        format: double
    additionalProperties: false
  x-any:
    properties: {}
  test:
    properties:
      id:
        type: number
        format: double
    additionalProperties: false
swagger: '2.0'
info:
  x-ibm-name: test-apic-2
  version: 1.0.0
  title: test-apic-2
schemes:
  - https
host: $(catalog.host)
basePath: /api
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecretHeader:
    in: header
    name: X-IBM-Client-Secret
    type: apiKey
security:
  - clientIdHeader: []
    clientSecretHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:4001'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)
