paths:
  /T1s:
    post:
      tags:
        - T1
      summary: Create a new instance of the model and persist it into the data source.
      operationId: T1.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/T1'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/T1'
      deprecated: false
    put:
      tags:
        - T1
      summary: Update an existing model instance or insert a new one into the data source.
      operationId: T1.upsert
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/T1'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/T1'
      deprecated: false
    get:
      tags:
        - T1
      summary: Find all instances of the model matched by filter from the data source.
      operationId: T1.find
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/T1'
      deprecated: false
  '/T1s/{id}/exists':
    get:
      tags:
        - T1
      summary: Check whether a model instance exists in the data source.
      operationId: 'T1.exists__get_T1s_{id}_exists'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
  '/T1s/{id}':
    head:
      tags:
        - T1
      summary: Check whether a model instance exists in the data source.
      operationId: 'T1.exists__head_T1s_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
    get:
      tags:
        - T1
      summary: Find a model instance by id from the data source.
      operationId: T1.findById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: filter
          in: query
          description: Filter defining fields and include
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/T1'
      deprecated: false
    delete:
      tags:
        - T1
      summary: Delete a model instance by id from the data source.
      operationId: T1.deleteById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    put:
      tags:
        - T1
      summary: Update attributes for a model instance and persist it into the data source.
      operationId: T1.prototype.updateAttributes
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/T1'
        - name: id
          in: path
          description: PersistedModel id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/T1'
      deprecated: false
  /T1s/findOne:
    get:
      tags:
        - T1
      summary: Find first instance of the model matched by filter from the data source.
      operationId: T1.findOne
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/T1'
      deprecated: false
  /T1s/update:
    post:
      tags:
        - T1
      summary: Update instances of the model matched by where from the data source.
      operationId: T1.updateAll
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/T1'
      responses:
        '200':
          description: Request was successful
          schema:
            description: The number of instances updated
            type: object
      deprecated: false
  /T1s/count:
    get:
      tags:
        - T1
      summary: Count instances of the model matched by where from the data source.
      operationId: T1.count
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              count:
                type: number
                format: double
      deprecated: false
  /T1s/change-stream:
    post:
      tags:
        - T1
      summary: Create a change stream.
      operationId: T1.createChangeStream__post_T1s_change-stream
      parameters:
        - name: options
          in: formData
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: file
      deprecated: false
    get:
      tags:
        - T1
      summary: Create a change stream.
      operationId: T1.createChangeStream__get_T1s_change-stream
      parameters:
        - name: options
          in: query
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: file
      deprecated: false
definitions:
  T1:
    properties:
      p1:
        description: '-- second --'
        type: number
        format: double
      id:
        type: number
        format: double
    additionalProperties: false
  x-any:
    properties: {}
swagger: '2.0'
info:
  x-ibm-name: first
  version: 1.0.0
  title: first
schemes:
  - https
host: $(catalog.host)
basePath: /api
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecretHeader:
    in: header
    name: X-IBM-Client-Secret
    type: apiKey
security:
  - clientIdHeader: []
    clientSecretHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:4001'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)
