paths:
  /Cars:
    post:
      tags:
        - Car
      summary: Create a new instance of the model and persist it into the data source.
      operationId: Car.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Car'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Car'
      deprecated: false
    patch:
      tags:
        - Car
      summary: Patch an existing model instance or insert a new one into the data source.
      operationId: Car.patchOrCreate
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Car'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Car'
      deprecated: false
    put:
      tags:
        - Car
      summary: Replace an existing model instance or insert a new one into the data source.
      operationId: Car.replaceOrCreate__put_Cars
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Car'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Car'
      deprecated: false
    get:
      tags:
        - Car
      summary: Find all instances of the model matched by filter from the data source.
      operationId: Car.find
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Car'
      deprecated: false
  /Cars/replaceOrCreate:
    post:
      tags:
        - Car
      summary: Replace an existing model instance or insert a new one into the data source.
      operationId: Car.replaceOrCreate__post_Cars_replaceOrCreate
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Car'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Car'
      deprecated: false
  /Cars/upsertWithWhere:
    post:
      tags:
        - Car
      summary: Update an existing model instance or insert a new one into the data source based on the where criteria.
      operationId: Car.upsertWithWhere
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Car'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Car'
      deprecated: false
  '/Cars/{id}/exists':
    get:
      tags:
        - Car
      summary: Check whether a model instance exists in the data source.
      operationId: 'Car.exists__get_Cars_{id}_exists'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
  '/Cars/{id}':
    head:
      tags:
        - Car
      summary: Check whether a model instance exists in the data source.
      operationId: 'Car.exists__head_Cars_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
    get:
      tags:
        - Car
      summary: 'Find a model instance by {{id}} from the data source.'
      operationId: Car.findById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: filter
          in: query
          description: 'Filter defining fields and include - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Car'
      deprecated: false
    put:
      tags:
        - Car
      summary: Replace attributes for a model instance and persist it into the data source.
      operationId: 'Car.replaceById__put_Cars_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Car'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Car'
      deprecated: false
    delete:
      tags:
        - Car
      summary: 'Delete a model instance by {{id}} from the data source.'
      operationId: Car.deleteById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    patch:
      tags:
        - Car
      summary: Patch attributes for a model instance and persist it into the data source.
      operationId: Car.prototype.patchAttributes
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Car'
        - name: id
          in: path
          description: Car id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Car'
      deprecated: false
  '/Cars/{id}/replace':
    post:
      tags:
        - Car
      summary: Replace attributes for a model instance and persist it into the data source.
      operationId: 'Car.replaceById__post_Cars_{id}_replace'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Car'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Car'
      deprecated: false
  /Cars/findOne:
    get:
      tags:
        - Car
      summary: Find first instance of the model matched by filter from the data source.
      operationId: Car.findOne
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Car'
      deprecated: false
  /Cars/update:
    post:
      tags:
        - Car
      summary: 'Update instances of the model matched by {{where}} from the data source.'
      operationId: Car.updateAll
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Car'
      responses:
        '200':
          description: Request was successful
          schema:
            description: Information related to the outcome of the operation
            type: object
            properties:
              count:
                description: The number of instances updated
                type: number
                format: double
      deprecated: false
  /Cars/count:
    get:
      tags:
        - Car
      summary: Count instances of the model matched by where from the data source.
      operationId: Car.count
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              count:
                type: number
                format: double
      deprecated: false
definitions:
  Car:
    properties:
      Model:
        type: string
      Year:
        type: number
        format: double
      id:
        type: string
    additionalProperties: false
  x-any:
    properties: {}
basePath: /api
swagger: '2.0'
info:
  x-ibm-name: cloudant-79
  version: 1.0.0
  title: cloudant-79
schemes:
  - https
host: $(catalog.host)
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecretHeader:
    in: header
    name: X-IBM-Client-Secret
    type: apiKey
security:
  - clientIdHeader: []
    clientSecretHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:4001'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)
