product: 1.0.0
info:
  name: product-test-1
  title: product-test-1
  version: 1.0.0
visibility:
  view:
    type: public
  subscribe:
    type: authenticated
plans:
  default:
    title: Default Plan
    description: Default Plan
    approval: false
    rate-limits:
      per-minute:
        value: 100/minute
        hard-limit: false
