swagger: '2.0'
info:
  version: 1.0.0
  title: test-api
  x-ibm-name: test-api
host: $(catalog.host)
basePath: /
paths: {}
securityDefinitions:
  clientID:
    description: ''
    in: header
    name: X-IBM-Client-Id
    type: apiKey
security:
  - clientID: []
x-ibm-configuration:
  assembly:
    execute:
      - invoke:
          target-url: $(target-url)
